
CREATE DATABASE STUDENTS;
USE STUDENTS;
CREATE TABLE `DETAILS` (
  `ROLL_NO` int(3) NOT NULL,
  `NAME` varchar(25) DEFAULT NULL,
  `DOB` date DEFAULT NULL,
  PRIMARY KEY (`ROLL_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
